version: 2.1
orbs:
  fn-cli: mant1c0re/fn-cli@dev:0.0.11
jobs:
  build:
    docker:
      - image: 'circleci/python:3.6'
    steps:
      - fn-cli/install
      - fn-cli/configure
# Commenting this as app created, but can't get ensure to work
#      - fn-cli/ensure-app:
#         appname: superduperfnapp
      - run: cd ../ | ls
      - run:
          name: "Deploy Fn"
          command: fn deploy --app superduperfnapp --working-dir ./hellofn
