version: 2.1
orbs:
  fn-cli: mant1c0re/fn-cli@dev:0.0.4
jobs:
  build:
    docker:
      - image: 'circleci/python:3.6'
    steps:
      - fn-cli/install
      - fn-cli/configure
      - run: 'echo /tmp/oci_api_key.pem'
      - fn-cli/list-apps
