version: 2.1
orbs:
  fn-cli: manticore/fn-cli@dev:0.0.6
jobs:
  build:
    docker:
      - image: 'circleci/python:3.6'
    steps:
      - fn-cli/install
      - fn-cli/configure
      - run:
          name: "Create App"
          command: fn create app superduperfnapp --annotation oracle.com/oci/subnetIds="[\"$FN_APP_SUBNET_ID\"]"
      -run:
        name: "Deploy Fn"
        command: fn deploy --app superduperfnapp --working-dir ./hellofn
