version: 2.1
orbs:
  fn-cli: mant1c0re/fn-cli@dev:0.0.11
jobs:
  build:
    docker:
      - image: 'circleci/python:3.6'
    steps:
      - fn-cli/install
      - fn-cli/configure
      - checkout
# Commenting this as app created, but can't get ensure to work
#      - fn-cli/ensure-app:
#         appname: superduperfnapp
      # update Docker
      - run: |
          docker version
          sudo service docker stop
          curl -fsSL https://get.docker.com/ | sudo sh
      - run: docker version
      - run:
          name: "Deploy Fn"
          command: cd hellofn && fn deploy --app superduperfnapp
