version: 2.1
orbs:
  fn-cli: manticore/fn-cli@dev:0.0.5
jobs:
  build:
    docker:
      - image: 'circleci/python:3.6'
    steps:
      - fn-cli/install
      - fn-cli/configure
      - fn-cli/list-apps
