version: 2.1
orbs:
  fn-cli: mant1c0re/fn-cli@dev:0.0.11
jobs:
  build:
    machine: true
    working_directory: ~/superduperfnapp
    steps:
      - fn-cli/install
      - fn-cli/configure
      - checkout
# Commenting this as app created, but can't get ensure to work
#      - fn-cli/ensure-app:
#         appname: superduperfnapp
      # update Docker
      - run: |
          docker version
          sudo service docker stop
          curl -fsSL https://get.docker.com/ | sudo sh
      - run: docker version
      - run: printenv DOCKER_PASS | docker login $PRIVATE_REGISTRY -u $DOCKER_USER --password-stdin
      - run:
          name: "Deploy Fn"
          command: fn deploy --app superduperfnapp --working-dir ~/superduperfnapp/hellofn
      - run:
          name: "Invoke Fn"
          command: fn invoke superduperfnapp hellofn
