version: 2.1
orbs:
  fn-cli: manticore/fn-cli@dev:0.0.7
jobs:
  build:
    docker:
      - image: 'circleci/python:3.6'
    steps:
      - fn-cli/install
      - fn-cli/configure
      - fn-cli/ensure-app:
          appname: superduperfnapp
      - run:
          name: "Deploy Fn"
          command: fn deploy --app superduperfnapp --working-dir ./hellofn
